#!/usr/bin/env ruby

require 'socket'

RSA_CLIENT_PORT = 8080
HOST = 'localhost'

rsa_client = TCPSocket.open(HOST, RSA_CLIENT_PORT)

while (message = gets)
  rsa_client.print(message)
end

rsa_client.close
