#!/usr/bin/env ruby

require 'socket'
require './rsa'

PORT = 8080
RSA_SERVER_PORT = 20000
RSA_SERVER_HOST = 'localhost'

server = TCPServer.open PORT
rsa_server = TCPSocket.open(RSA_SERVER_HOST, RSA_SERVER_PORT)

$n = rsa_server.gets.to_i
puts "Received public modulus n=#{$n}"

def encrypt(message)
  raise "Don't know the public key" if $n.nil?
  RSA.encrypt(message.chomp, $n)
end

loop do
  Thread.start(server.accept) do |app|
    app = server.accept
    puts "App client has connected."

    while (message = app.gets)
      puts "Received message: #{message}"

      cypher = encrypt(message)
      rsa_server.puts(cypher)
      puts "Sent encrypted message: #{cypher}"
    end

    app.close
  end
end
