#!/usr/bin/env ruby

require 'socket'
require './rsa'

PORT = 20000
BITS = 256

server = TCPServer.open PORT
$n, $e, $d = RSA.generate_keys BITS

def decrypt(message)
  RSA.decrypt(message.chomp.to_i, $n, $d)
end

loop do
  # Thread.start(server.accept) do |socket|
    socket = server.accept
    puts "RSA client has connected."

    socket.puts($n)
    puts "Sent public modulus n=#{$n}"

    while (message = socket.gets)
      puts "Received encrypted message: #{message}"
      puts "Decrypted message: #{decrypt(message)}"
    end

    socket.close
  # end
end
