#!/usr/bin/env ruby

require 'gserver'
require 'mini-smtp-server'
require 'mail'
require 'optparse'

$options = {}

usage = <<EOS
Usage: ./smtp-gateway [options] kw_file1 [kw_file2 ...]

    Example
        ./smtp-gateway filter.txt --host localhost:1234

EOS

option_parser = OptionParser.new do |opts|
  opts.banner = usage

  opts.on('--host HOST:PORT') do |host|
    $options[:host], $options[:port] = host.strip.split(':')
  end

  opts.on('--relay HOST:PORT') do |host|
    $options[:replay_host], $options[:replay_port] = host.strip.split(':')
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

HELP = option_parser.help
option_parser.parse!

if ARGV.empty?
  puts HELP
  exit
end

KEYWORDS = ARGF.readlines.map(&:chomp).reject(&:empty?)

RELAY_HOST = $options[:replay_host] || 'localhost'
RELAY_PORT = $options[:replay_port] || 1025

GATEWAY_HOST = $options[:host] || 'localhost'
GATEWAY_PORT = $options[:port] || 2525

Mail.defaults do
  delivery_method :smtp, address: RELAY_HOST, port: RELAY_PORT
end

class KeywordFilter
  attr_reader :keywords, :replace

  def initialize(keywords = [])
    @keywords = keywords
    @replace = '[redacted]'
  end

  def apply!(mail)
    mail.subject redact(mail.subject)
    mail.body    redact(mail.body)
  end

  private

  def redact(str)
    str = str.to_s.clone

    keywords.each do |kw|
      str.gsub!(Regexp.new(kw), replace)
    end

    str
  end
end

class SMTPGateway < MiniSmtpServer
  def new_message_event(message_hash)
    mail = Mail.read_from_string(message_hash.fetch(:data))

    filter = KeywordFilter.new KEYWORDS
    filter.apply!(mail)

    mail.deliver
    puts mail
  end
end

server = SMTPGateway.new(GATEWAY_PORT, GATEWAY_HOST)
server.start

msg = <<~EOS
  SMTP Gateway 9000
  =================

  Listening: smtp://#{GATEWAY_HOST}:#{GATEWAY_PORT}
  Relay: smtp://#{RELAY_HOST}:#{RELAY_PORT}
  Keywords: #{KEYWORDS.count}

EOS
puts msg

server.join
