#!/usr/bin/env ruby

require 'mail'
require 'optparse'

$options = {}
option_parser = OptionParser.new do |opts|
  opts.on('-f', '--from FROM') do |from|
    $options[:from] = from.strip
  end

  opts.on('-t', '--to TO') do |to|
    $options[:to] = to.strip
  end

  opts.on('-s', '--subject SUBJECT') do |subject|
    $options[:subject] = subject.strip
  end

  opts.on('-b', '--body BODY') do |body|
    $options[:body] = body.strip
  end

  opts.on('-a', '--attach FILE') do |file|
    $options[:files] = [file.strip]
  end

  opts.on('-v', '--virus', "Mail viruses") do
    $options[:files] = ['not_a_virus.exe', 'not_a_virus_for_real.txt']
  end

  opts.on('--host HOST:PORT') do |host|
    $options[:host], $options[:port] = host.strip.split(':')
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

option_parser.parse!

host = $options[:host] || 'localhost'
port = $options[:port] || 2525

from    = $options[:from] || 'spongebob@bikini.org'
to      = $options[:to] || 'foo@bar.com'
subject = $options[:subject] || 'super secret stuff'
body    = $options[:body] || 'hey user, you wanna hang out and do some super secret stuff and exchange secrets?'

mail = Mail.new do
  from    from
  to      to
  subject subject
  body    body
end

($options[:files] || []).each do |file|
  mail.add_file(file)
end

mail.delivery_method :smtp, address: host, port: port, tls: false,
  enable_starttls_auto: false, enable_starttls: false

mail.deliver
puts mail
